source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'activerecord'
gem 'activesupport'
gem 'dotenv'
gem 'mysql2'
gem 'require_all', '<2.0.0'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'

group :development, :test do
  gem 'byebug'
  gem 'coveralls_reborn', '~> 0.16.0', require: false
  gem 'factory_bot'
  gem 'foreman', require: false
  gem 'forgery'
  gem 'fuubar'
  gem 'mock_redis'
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-json_expectations'
  gem 'rubocop', require: false
  gem 'rufo'
  gem 'simplecov', require: false
  gem 'simplecov-cobertura'
  gem 'webmock'
  gem 'pry-nav'
end
