FROM ruby:2.5

RUN apt-get update
RUN gem install bundler -v 1.17.3
RUN gem install foreman
RUN gem install ruby-debug-ide -v 0.7.3

ADD Gemfile .
ADD Gemfile.lock .

RUN bundle install

WORKDIR /home/web/project
CMD ["foreman", "start"]